// The machine code generated by your program should go here

// push constants 2, 3 and 5 onto the stack
@2
D = A 
@SP
AM = M + 1
A = A - 1
M = D
@3
D = A
@SP
AM = M + 1
A = A - 1
M = D
@5
D = A
@SP
AM = M + 1
A = A - 1
M = D

// pop a value off the stack and store in THAT 1
@1
D = A
@THAT
D = D + M
@TEMP
M = D
@SP
AM = M - 1
D = M
@TEMP
A = M
M = D

(END)
    @END
    0;JMP