// The machine code generated by your program should go here

// push constants 2, 3 and 5 onto the stack
@2
D = A 
@SP
AM = M + 1
A = A - 1
M = D
@3
D = A
@SP
AM = M + 1
A = A - 1
M = D
@5
D = A
@SP
AM = M + 1
A = A - 1
M = D

// pop a value off the stack and store in RAM[16]
@SP
AM = M - 1
D = M
@TEMP
M = D       // RAM[16] = 3

// pop 2 off stack and calculate sum
@SP
AM = M - 1
D = M       // D-register stores 2
@TEMP 
D = D + M   // D = 2 + RAM[16] = 2 + 3

// push sum onto stack
@SP
AM = M + 1
A = A - 1
M = D

(END)
    @END
    0;JMP