// The machine code generated by your program should go here

// push constants 2, 3 and 3 onto the stack
@20
D = A 
@SP
AM = M + 1
A = A - 1
M = D
@30
D = A
@SP
AM = M + 1
A = A - 1
M = D
@30
D = A
@SP
AM = M + 1
A = A - 1
M = D

// pop a value off the stack and store in RAM[16]
@SP
AM = M - 1
D = M
@TEMP
M = D       // RAM[16] = 3

// pop 3 off stack and compare
@SP
AM = M - 1
D = M       // D-register stores 3
@TEMP 
D = D - M   // D = 3 - RAM[16] = 3 - 3 = 0
@EQUAL
D;JEQ       // jump to EQUAL if D = 0

// otherwise, push FALSE (0) onto stack
@0
D = A
@SP
AM = M + 1
A = A - 1
M = D
@END
0;JMP

(EQUAL)
// push TRUE (-1) onto stack
D = -1
@SP
AM = M + 1
A = A - 1
M = D
@END
0;JMP

(END)
@END
0;JMP